In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('decision_tree.csv')
df

person  age  salary  buy/notbuy
0        1    1       1           0
1        2    2       1           0
2        3    3       2           1
3        4    3       2           1
4        5    1       1           0
5        6    2       3           1
6        7    1       1           0
7        8    1       2           0
8        9    2       3           1
9       10    2       2           1
10      11    3       1           0
11      12    3       2           1
12      13    3       3           1
13      14    1       2           0
14      15    2       1           0
15      16    1       3           0
16      17    1       2           0
17      18    2       1           1
18      19    2       3           1
19      20    3       1           0
20      21    1       2           0
21      22    1       1           0
22      23    2       3           1
23      24    1       2           0
24      25    3       1           0
25      26    1       3           0
26      27    3       1           0
27      28    2       2           1
28      29    2       2           1
29      30    1       1           0
30      31    1       3           0
31      32    3       2           1
32      33    3       3           1
33      34    1       3           0
34      35    2       2           1
35      36    1       2           0
36      37    3       1           0
37      38    3       1           0
38      39    1       3           0
39      40    2       2           1
40      41    1       3           0
41      42    2       2           1
42      43    3       1           0
43      44    3       1           0
44      45    2       2           1
45      46    1       3           0
46      47    1       2           1
47      48    3       1           0
48      49    2       3           1
49      50    3       2           1

In [3]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [4]:
print ("Dataset Length: ", len(df))
print ("Dataset Shape: ", df.shape)

Dataset Length:  50
Dataset Shape:  (50, 4)


In [5]:
X = df.values[:, 1:-1]
Y = df.values[:, -1]
Y=Y.astype('int')

In [6]:
X

array([[1, 1],
       [2, 1],
       [3, 2],
       [3, 2],
       [1, 1],
       [2, 3],
       [1, 1],
       [1, 2],
       [2, 3],
       [2, 2],
       [3, 1],
       [3, 2],
       [3, 3],
       [1, 2],
       [2, 1],
       [1, 3],
       [1, 2],
       [2, 1],
       [2, 3],
       [3, 1],
       [1, 2],
       [1, 1],
       [2, 3],
       [1, 2],
       [3, 1],
       [1, 3],
       [3, 1],
       [2, 2],
       [2, 2],
       [1, 1],
       [1, 3],
       [3, 2],
       [3, 3],
       [1, 3],
       [2, 2],
       [1, 2],
       [3, 1],
       [3, 1],
       [1, 3],
       [2, 2],
       [1, 3],
       [2, 2],
       [3, 1],
       [3, 1],
       [2, 2],
       [1, 3],
       [1, 2],
       [3, 1],
       [2, 3],
       [3, 2]])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 25)

In [8]:
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=3)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [9]:
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[0 0 0 1 0 0 1 0 0 1]


In [10]:
confusion_matrix(y_test, y_pred)

array([[5, 0],
       [2, 3]])

In [11]:
accuracy_score(y_test,y_pred)*100

80.0

In [12]:
test= clf_gini.predict([[3,2]])
test

array([1])

In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      1.00      0.83         5
           1       1.00      0.60      0.75         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10

